### ISSUE TITLE
How to get openAiApiKey?

### ISSUE THREAD

**Issue by MasilamaniSeenivasan** [Serviceware/azure-devops-ai-pipeline#32]

**Comment by antoniobergas** [comment]
Hi @MasilamaniSeenivasan,

Regarding the openAiApiKey, this is a credential you'll need to procure from your personal or company account with OpenAI. You can obtain it through the official OpenAI platform at https://platform.openai.com/. They provide detailed instructions on acquiring and managing API keys there. 

Nonetheless, including some annotations in the documentation regarding this matter would be beneficial for users. Thank you for bringing this to our attention. We'll consider adding more guidance to assist users in obtaining their OpenAI API keys. Your feedback is much appreciated!

**Comment by MasilamaniSeenivasan** [comment]
I created a new api key after signup in openai portal, thanks

**Comment by Vitanakpapa** [comment]
#32
